import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>This is just a page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Hello world</div>
      </main>
    </>
  )
}
