version: '3.8'

services:

  postgres:
    image: 'postgres:15.1-alpine'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_jobsearch_vol:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - postgres_network

  redis:
    restart: always
    image: 'redis:7.0.8-alpine'
    ports:
      - 6379:6379
    networks:
      - redis_network

  localstack:
    container_name: localstack_main
    image: 'localstack/localstack:latest'
    ports:
      - 127.0.0.1:4566:4566            # LocalStack Gateway
      - 127.0.0.1:4510-4559:4510-4559  # external services port range
    environment:
      - SERVICES=s3,ses
      - DEBUG=${DEBUG:-1}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/create_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh

  # pgadmin:
  #   image: 'dpage/pgadmin4'
  #   ports:
  #     - 81:80
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin_vol:/var/lib/pgadmin
  #   env_file:
  #     - .env
  #   networks:
  #     - postgres_network

networks:
  postgres_network:
    driver: bridge
  redis_network:

volumes:
  pg_jobsearch_vol:
  # pgadmin_vol:
